name: Build and Store Image to GHCR

on:
  push:
    branches: ["main"] # Chạy khi bạn push code lên main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Quyền hạn cần thiết để GitHub Actions ghi được vào Package
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # Đăng nhập vào GHCR dùng token có sẵn của hệ thống
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Vừa build vừa đẩy lên kho lưu trữ
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # Đặt tag cho image (ví dụ: ghcr.io/hoidanit/my-app:latest)
          tags: |
            ghcr.io/${{ github.repository }}:v1
            ghcr.io/${{ github.repository }}:${{ github.sha }}
